const fs=require('node:fs');const assert=require('node:assert/strict');const path=require('node:path');
const root=path.join(__dirname,'../..');
const ui=fs.readFileSync(path.join(__dirname,'../app/src/main/assets/phase9-field-ui.js'),'utf8');
const pwa=fs.readFileSync(path.join(root,'pwa/index.html'),'utf8');
const sw=fs.readFileSync(path.join(root,'pwa/sw.js'),'utf8');
const manifest=fs.readFileSync(path.join(root,'pwa/manifest.webmanifest'),'utf8');
assert.match(ui,/const BRAND='EkinCep'/);assert.match(ui,/min-height:52px/);assert.match(ui,/prefers-contrast:more/);assert.equal(ui.includes("replace(/Tarla\\s*Pusula/gi,BRAND)"),true);
assert.match(ui,/Çırçır \/ ginleme/);assert.match(ui,/Fındık toplama işçiliği/);assert.match(ui,/Kırma \/ dizme işçiliği/);assert.match(ui,/Tarım Kredi ayni kredi/);assert.match(ui,/Çek \/ senet/);assert.match(ui,/debtCreditType/);
assert.match(pwa,/<title>EkinCep — Tarla defteri ve saha takibi<\/title>/);assert.match(pwa,/meta name="description"/);assert.match(pwa,/property="og:image"/);assert.match(pwa,/class="skeleton"/);assert.match(pwa,/indexedDB/);assert.match(pwa,/ekincep-last-weather-v1/);
assert.match(sw,/caches\.open/);assert.match(sw,/api\.open-meteo\.com/);assert.match(sw,/raw\.githubusercontent\.com/);assert.match(sw,/networkFirst/);assert.match(manifest,/"short_name":"EkinCep"/);
console.log('Phase 9 field ergonomics, crop-awareness and Turkey debt assertions passed');