const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'../..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const loader=read('pwa/app-loader.js');
const sw=read('pwa/sw.js');
const home=read('android-web-shell/app/src/main/assets/phase11-home.js');
const sat=read('android-web-shell/app/src/main/assets/phase11-satellite.js');
const ndvi=read('pwa/api/ndvi.js');
const fuel=read('pwa/api/fuel.js');

assert.equal(/raw\.githubusercontent\.com|cdn\.jsdelivr\.net|raw\.githack\.com/.test(loader),false,'production loader must not fetch runtime code remotely');
assert.equal(/\beval\s*\(/.test(loader),false,'production loader must not eval runtime code');
assert.match(loader,/ASSET_ROOT='\/assets\/'/);
assert.match(loader,/phase11-home\.js/);
assert.match(loader,/phase11-satellite\.js/);
assert.equal(/raw\.githubusercontent\.com|cdn\.jsdelivr\.net/.test(sw),false,'service worker must not cache remote app code');
assert.match(sw,/\/assets\/phase11-home\.js/);
for(const label of ['Bugün','Bu sezon','Tarlalar','Canlı veriler','Hızlı işler'])assert.match(home,new RegExp(label));
assert.match(home,/ESKİ VERİ/);
assert.match(sat,/Bitki sağlığı · NDVI/);
assert.match(sat,/Canlı kamera değildir/);
assert.match(sat,/method:'POST'/);
assert.match(ndvi,/process\.env\.CDSE_CLIENT_ID/);
assert.match(ndvi,/process\.env\.CDSE_CLIENT_SECRET/);
assert.match(ndvi,/req\.method!=='POST'/);
assert.equal(/client_secret\s*[:=]\s*['"][^'"]+['"]/.test(ndvi),false,'Copernicus secret must never be hard-coded');
assert.match(ndvi,/Sentinel-2 L2A/);
assert.match(ndvi,/resolutionMeters:10/);
assert.match(fuel,/`\$\{o\.day\}\.\$\{o\.month\}\.\$\{o\.year\}`/);
assert.match(fuel,/Türkiye geneli resmî bülten/);
assert.equal(fs.existsSync(path.join(root,'pwa/assets/phase11-home.js')),true);
assert.equal(fs.existsSync(path.join(root,'pwa/assets/phase11-satellite.js')),true);
console.log('Phase 11 assertions: 23 passed');
