const fs=require('node:fs');
const assert=require('node:assert/strict');
const path=require('node:path');
const root=path.join(__dirname,'../..');
const assetRoot=path.join(__dirname,'../app/src/main/assets');
const ui=fs.readFileSync(path.join(assetRoot,'phase10-command-center.js'),'utf8');
const android=fs.readFileSync(path.join(__dirname,'../app/src/main/java/app/ciftcidefteri/web/MainActivity.java'),'utf8');
const pwa=fs.readFileSync(path.join(root,'pwa/index.html'),'utf8');
const sw=fs.readFileSync(path.join(root,'pwa/sw.js'),'utf8');

assert.match(ui,/__EKINCEP_PHASE10_COMMAND_CENTER__/);
assert.match(ui,/Bu sezon cebinde kalan/);
assert.match(ui,/ec10-financeHero/);
assert.match(ui,/ec10-todayRail/);
assert.match(ui,/ec10-cropLines/);
assert.match(ui,/ec10-fieldGrid/);
assert.match(ui,/ec10-dataRail/);
assert.match(ui,/ec10-toolChest/);
assert.match(ui,/cropSvg/);
assert.match(ui,/cotton/);
assert.match(ui,/corn/);
assert.match(ui,/wheat/);
assert.match(ui,/Piyasa/);
assert.match(ui,/Elindekiler/);
assert.match(ui,/Tarla havası/);
assert.match(ui,/prefers-reduced-motion/);
assert.match(ui,/min-height:72px/);
assert.doesNotMatch(ui,/field-hero\.webp/);
assert.match(android,/readAssetText\("phase10-command-center\.js"\)/);
assert.match(pwa,/'phase10-command-center\.js'/);
assert.match(pwa,/raw\.githack\.com/);
assert.match(pwa,/new URL\('\.\/assets\/'/);
assert.match(sw,/ekincep-pwa-v4/);
assert.match(sw,/api\.open-meteo\.com/);

console.log('Phase 10 EkinCep command center assertions: 24 passed');
